### ISSUE TITLE
Read Status Checklist

### ISSUE THREAD

**Issue by MrChaoCao** [MrChaoCao/GoRead#10]
- [ ] Books can be marked as read
- [ ] Books can be marked as unread (read status can be removed)

-----------------Bonus
- [ ] Users can favorite books
- [ ] Users can view all books they have read
