### ISSUE TITLE
Book Checklist

### ISSUE THREAD

**Issue by MrChaoCao** [MrChaoCao/GoRead#5]
- [x] Have book objects
- [x] Render book index page
- [x] Render book show page
- [x] Users can see relevant book attributes
