### ISSUE TITLE
Bookshelf checklist

### ISSUE THREAD

**Issue by MrChaoCao** [MrChaoCao/GoRead#7]
- [ ] Users can add books to shelves
- [ ] Users can remove books from shelves
- [ ] Users can see all shelves
- [ ] Users can see individual shelves
