### ISSUE TITLE
Review Checklist

### ISSUE THREAD

**Issue by MrChaoCao** [MrChaoCao/GoRead#8]
- [ ] Users can view reviews
- [ ] Users can add reviews
- [ ] Users can update reviews
- [ ] Users can delete reviews

------- Bonus
- [ ] Users can see reviews from other users
