### ISSUE TITLE
Readme Checklist

### ISSUE THREAD

**Issue by MrChaoCao** [MrChaoCao/GoRead#9]
- [ ] Readme contains link to live website
- [ ] Readme concisely explains the functionality of website
- [ ] Readme showcases unique features of website
- [ ] Readme includes multimedia features showcasing site functionality and design
- [ ] Readme discusses the technologies used to create site
- [ ] Readme includes plans for future site development
